name: 'Protolock check and update'
description: 'Checks protolock'
inputs:
  PATH:
    required: true
  PROTOLOCK_URL:
    description: "Download link for protolock tarball"
    default: "https://github.com/nilslice/protolock/releases/download/v0.15.0/protolock.20191021T032920Z.linux-amd64.tgz"
    required: true
  COMMIT:
    description: "Whether the protolock changes should be committed back to the repository. Requires git. Values: true | false"
    required: false
    default: false
  LOCKDIR:
    description: "DEPRECATED - use PATH instead. LOCKDIR is broken. The directory containing your proto.lock file"
    required: false
    default: .
runs:
  using: "composite"
  steps: 
    - run: |
        cd $PROTOPATH
        mkdir -p /protolock 
        if ! [ -f /protolock/protolock.tgz ]; then
          curl -L -o /protolock/protolock.tgz $PROTOLOCK_URL
        fi
        tar xzf /protolock/protolock.tgz
        ./protolock status
        if [ "$COMMIT" = "true" ]; then
          ./protolock commit
          git add proto.lock
          if [[ $(git diff --staged --quiet proto.lock)$? == 1 ]]; then 
            git commit -m "Update protolock status"
            git config user.email "ci@zepben.com"
            git config user.name "Zepben CI"
            git push 
          fi
        fi
      shell: bash
      env:
        PROTOPATH: ${{ inputs.PATH }}
        PROTOLOCK_URL: ${{ inputs.PROTOLOCK_URL }}
        COMMIT: ${{ inputs.COMMIT }}
        LOCKDIR: ${{ inputs.LOCKDIR }}
